### ISSUE TITLE
you index in order_data_t struct is no use ,because every connection will create a new request,

### ISSUE THREAD

**Issue by fankeke** [flygoast/ngx_http_upstream_order#1]

**Comment by fankeke** [comment]
your index in order_data_t struct  is no use ,because every connection will create a new request,
so the  order_data will be an new struct . so the index will be always  0 when choose a bakend server .

so ,index must  be placed  in the peers_t struct . because peers_t struct has only one instance during all the time. :)

**Comment by flygoast** [comment]
It used to choose a backend server according the order in upstream in one request, not globally. Only
if the backend at before failed, the later would be retried.

**Comment by fankeke** [comment]
I see your point. you mean your "order" only works in the same one request (if the choose backend server for it and failed ,then choose another backend in order for the same request ) .

if a new request comes, always choose the same backend  in your first  try

thanks.
